### ISSUE TITLE
not ipynb format

### ISSUE THREAD

**Issue by odewahn** [esztiorm/OrioleNotebooks#1]
Hi.  `AnomalyDetection_NBusa.ipynb` appears to be an HTML file, not a notebook.  Can you also add the actual ipynb file itself?

**Comment by esztiorm** [comment]
I apologize, I am just seeing this now. That is the only version I have of the file. However, I received a notebook version of SparkStreamingDemo.ipynb. Can we start with that? That is actually the notebook I should review.

**Comment by esztiorm** [comment]
I turned on email notifications, so I will now notice right away when you write.

**Comment by esztiorm** [comment]
For this particular notebook, Alex recommends Jupyter's pyspark docker image:
https://github.com/jupyter/docker-stacks/tree/master/pyspark-notebook

**Comment by esztiorm** [comment]
Hi Andrew - I installed docker locally and ran through Alex's notebook. All worked well. Not sure I need anything from you at this point? Please enjoy your PTO and sorry that I bothered you during vacation!
ps - This was my first time using docker. Amazing! I love it!
